package group3.en.stuattendance.Auditmanager.Mapper;

import group3.en.stuattendance.Auditmanager.DTO.AuditlogDto;
import group3.en.stuattendance.Auditmanager.Model.Auditlog;
import org.springframework.stereotype.Component;

import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

@Component
public class AuditlogMapper {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // ── Entity → DTO ──────────────────────────────────────────────────────────
    public AuditlogDto toDto(Auditlog auditlog) {
        if (auditlog == null) return null;

        return AuditlogDto.builder()
                .auditId(auditlog.getAuditId())
                .username(auditlog.getUsername())
                .action(auditlog.getAction())
                .target(auditlog.getTarget())
                .category(auditlog.getCategory())
                .ipAddress(auditlog.getIpAddress())
                .timestamp(auditlog.getTimestamp() != null
                        ? auditlog.getTimestamp().format(FORMATTER)
                        : "")
                .build();
    }

    // ── DTO → Entity ──────────────────────────────────────────────────────────
    // auditId and timestamp are intentionally skipped:
    // - auditId   → auto-generated by the database (@GeneratedValue)
    // - timestamp → auto-set by Spring Auditing (@CreatedDate)
    public Auditlog toEntity(AuditlogDto dto) {
        if (dto == null) return null;

        return Auditlog.builder()
                .username(dto.getUsername())
                .action(dto.getAction())
                .target(dto.getTarget())
                .category(dto.getCategory())
                .ipAddress(dto.getIpAddress())
                .build();
    }

    // ── List<Entity> → List<DTO> ──────────────────────────────────────────────
    public List<AuditlogDto> toDtoList(List<Auditlog> auditlogs) {
        if (auditlogs == null) return List.of();

        return auditlogs.stream()
                .map(this::toDto)
                .collect(Collectors.toList());
    }
}